project:
  type: website

website:
  title: "Wenjium"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/wenjium88-png
      

  page-footer: 
      left: "© 2026 Wenjium"
      right: "Built with Quarto"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    smooth-scroll: true



